version: '3'

services:
  myapp-main:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golf_tournament
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: H3r31$@$tup1dp@$$w0rd
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: golf-club-tournament
    environment:
      MYSQL_DATABASE: golf_tournament
      MYSQL_ROOT_PASSWORD: H3r31$@$tup1dp@$$w0rd
    ports:
      - "3306:3306"


