version: '3'
services:
  myapp-main:
    image: bptracking:latest
    ports:
      - 8080:8080
    environment:
      #      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/
      - spring.datasource.url=jdbc:mysql://
      - spring.datasource.password=jordan1234
      - spring.datasource.username=admin